added Azure credentials to Test Server configuration stage

diff --git a/pipeline/zedePacketTest.jenkinsfile b/pipeline/zedePacketTest.jenkinsfile
--- a/pipeline/zedePacketTest.jenkinsfile
+++ b/pipeline/zedePacketTest.jenkinsfile
@@ -182,97 +182,99 @@ pipeline {
     stage('Set up Test Client and Server for all test cases') {
       when { expression { params.SETUP_CLIENT_SERVER }}
       steps {
-        // Wait 5 min for the Ziti Controller to boot up and configure itself
-        sh '''
-        eval sleep 5m
-        '''
-        // Set up security rules to allow tcp/5201 on App Server
-        sh '''
-        set -Eeuxo pipefail
-        eval python3 quickstarts/docs/python/azure/azure_manage_security_group.py --action update --rules "tcp,5201" --sg_name VM${SERVER_LOCATION}01
-        '''
-        // Add Public Client, Server and ZEDE IPs to the hosts file for Ansible
-        sh '''
-        set -Eeuxo pipefail
-        echo "[zede]" >> quickstarts/docs/ansible/hosts
-        echo `terraform output -json | jq -j .${ZEDE_NAME}_public_ips.value[][]` >> quickstarts/docs/ansible/hosts
-        echo "[zede-client]" >| quickstarts/docs/ansible/hosts
-        echo `terraform output -json | jq -j .VM${CLIENT_LOCATION}01_public_ips.value[][]` >> quickstarts/docs/ansible/hosts
-        echo "[app-server]" >> quickstarts/docs/ansible/hosts
-        echo `terraform output -json | jq -j .VM${SERVER_LOCATION}01_public_ips.value[][]` >> quickstarts/docs/ansible/hosts
-        cat quickstarts/docs/ansible/hosts
-        '''
-        //Configure vars for Private Server IP to be used in client -> server testing
-        sh '''
-        set -Eeuxo pipefail
-        serverIp=`eval terraform output -json | jq -j .VM${SERVER_LOCATION}01_private_ips.value[][]`
-        echo "serverIp: ${serverIp}" >| quickstarts/docs/ansible/roles/zede-client/vars/ip.yml
-        cat quickstarts/docs/ansible/roles/zede-client/vars/ip.yml
-        echo "serverIp: ${serverIp}" >| quickstarts/docs/ansible/roles/zede/vars/ip.yml
-        cat quickstarts/docs/ansible/roles/zede/vars/ip.yml
-        '''
-        // Run ansible playbook to configure client and zede
-        sh '''
-        set -Eeuxo pipefail
-        eval export ANSIBLE_HOST_KEY_CHECKING=False
-        cip=`eval terraform output -json | jq -j .${ZEDE_NAME}_public_ips.value[][]`
-        eval ansible-playbook -i quickstarts/docs/ansible/hosts quickstarts/docs/ansible/local.yml --tags zede,zede-client -u nfadmin -e zede=True -e zedeClient=True -e artifactoryApiKey=$ARTIFACTORY_API_KEY -e zitiVersion=$IMAGE_VERSION -e controllerIp=$cip -vv
-        '''
-        // Run ansible playbook to configure server
-        sh '''
-        set -Eeuxo pipefail
-        eval export ANSIBLE_HOST_KEY_CHECKING=False
-        eval ansible-playbook -i quickstarts/docs/ansible/hosts quickstarts/docs/ansible/local.yml --tags app-server -u nfadmin -e appServer=True
-        '''
-        // Configure iperf Service and add it to appwan
-        sh'''
-        set set -Eeuxo pipefail
-        serverIp=`eval terraform output -json | jq -j .VM${SERVER_LOCATION}01_private_ips.value[][]`
-        cip=`eval terraform output -json | jq -j .${ZEDE_NAME}_public_ips.value[][]`
-        export ZITI_PASSWORD=`eval jq -j .password ~/credentials.json`
-        # ziti edge controller login
-        token=`curl -sSX POST -H "Content-Type: application/json" -d "{\"username\": \"$ZITI_USERNAME\", \"password\": \"$ZITI_PASSWORD\"}" \
-              "https://$cip:1280/authenticate?method=password" --insecure  | jq -j ".data.token"`
-        # build a header with the session token
-        declare -a curlArgs=('-H' "Content-Type: application/json" '-H' "zt-session: $token")
-        clusters=`curl -sSX GET "${curlArgs[@]}" "https://$cip:1280/clusters" --insecure  | jq -j ".data"`
-        if [[ $clusters ]]; then
-          # find cluster uuid  for cluster demo-c01
-          cuuid=`echo $clusters | jq -j '.[] | select(.name=="demo-c01") | .id'`
-        else
-          echo " could not find cluster with name demo-c01"
-          exit 1
-        fi
-        gateways=`curl -sSX GET "${curlArgs[@]}" "https://$cip:1280/gateways" --insecure  | jq -j ".data"`
-        guuid=`echo $gateways | jq -j '.[] | select(.name=="ziti-gw01") | .id'`
-        if [[ $gateways ]]; then
-          # find the gateway uuid
+        withCredentials([usernamePassword(credentialsId: 'azure-edge-packer-builder', usernameVariable: 'ARM_CLIENT_ID', passwordVariable: 'ARM_CLIENT_SECRET')]) {
+          // Wait 5 min for the Ziti Controller to boot up and configure itself
+          sh '''
+          eval sleep 5m
+          '''
+          // Set up security rules to allow tcp/5201 on App Server
+          sh '''
+          set -Eeuxo pipefail
+          eval python3 quickstarts/docs/python/azure/azure_manage_security_group.py --action update --rules "tcp,5201" --sg_name VM${SERVER_LOCATION}01
+          '''
+          // Add Public Client, Server and ZEDE IPs to the hosts file for Ansible
+          sh '''
+          set -Eeuxo pipefail
+          echo "[zede]" >> quickstarts/docs/ansible/hosts
+          echo `terraform output -json | jq -j .${ZEDE_NAME}_public_ips.value[][]` >> quickstarts/docs/ansible/hosts
+          echo "[zede-client]" >| quickstarts/docs/ansible/hosts
+          echo `terraform output -json | jq -j .VM${CLIENT_LOCATION}01_public_ips.value[][]` >> quickstarts/docs/ansible/hosts
+          echo "[app-server]" >> quickstarts/docs/ansible/hosts
+          echo `terraform output -json | jq -j .VM${SERVER_LOCATION}01_public_ips.value[][]` >> quickstarts/docs/ansible/hosts
+          cat quickstarts/docs/ansible/hosts
+          '''
+          //Configure vars for Private Server IP to be used in client -> server testing
+          sh '''
+          set -Eeuxo pipefail
+          serverIp=`eval terraform output -json | jq -j .VM${SERVER_LOCATION}01_private_ips.value[][]`
+          echo "serverIp: ${serverIp}" >| quickstarts/docs/ansible/roles/zede-client/vars/ip.yml
+          cat quickstarts/docs/ansible/roles/zede-client/vars/ip.yml
+          echo "serverIp: ${serverIp}" >| quickstarts/docs/ansible/roles/zede/vars/ip.yml
+          cat quickstarts/docs/ansible/roles/zede/vars/ip.yml
+          '''
+          // Run ansible playbook to configure client and zede
+          sh '''
+          set -Eeuxo pipefail
+          eval export ANSIBLE_HOST_KEY_CHECKING=False
+          cip=`eval terraform output -json | jq -j .${ZEDE_NAME}_public_ips.value[][]`
+          eval ansible-playbook -i quickstarts/docs/ansible/hosts quickstarts/docs/ansible/local.yml --tags zede,zede-client -u nfadmin -e zede=True -e zedeClient=True -e artifactoryApiKey=$ARTIFACTORY_API_KEY -e zitiVersion=$IMAGE_VERSION -e controllerIp=$cip -vv
+          '''
+          // Run ansible playbook to configure server
+          sh '''
+          set -Eeuxo pipefail
+          eval export ANSIBLE_HOST_KEY_CHECKING=False
+          eval ansible-playbook -i quickstarts/docs/ansible/hosts quickstarts/docs/ansible/local.yml --tags app-server -u nfadmin -e appServer=True
+          '''
+          // Configure iperf Service and add it to appwan
+          sh'''
+          set set -Eeuxo pipefail
+          serverIp=`eval terraform output -json | jq -j .VM${SERVER_LOCATION}01_private_ips.value[][]`
+          cip=`eval terraform output -json | jq -j .${ZEDE_NAME}_public_ips.value[][]`
+          export ZITI_PASSWORD=`eval jq -j .password ~/credentials.json`
+          # ziti edge controller login
+          token=`curl -sSX POST -H "Content-Type: application/json" -d "{\"username\": \"$ZITI_USERNAME\", \"password\": \"$ZITI_PASSWORD\"}" \
+                "https://$cip:1280/authenticate?method=password" --insecure  | jq -j ".data.token"`
+          # build a header with the session token
+          declare -a curlArgs=('-H' "Content-Type: application/json" '-H' "zt-session: $token")
+          clusters=`curl -sSX GET "${curlArgs[@]}" "https://$cip:1280/clusters" --insecure  | jq -j ".data"`
+          if [[ $clusters ]]; then
+            # find cluster uuid  for cluster demo-c01
+            cuuid=`echo $clusters | jq -j '.[] | select(.name=="demo-c01") | .id'`
+          else
+            echo " could not find cluster with name demo-c01"
+            exit 1
+          fi
+          gateways=`curl -sSX GET "${curlArgs[@]}" "https://$cip:1280/gateways" --insecure  | jq -j ".data"`
           guuid=`echo $gateways | jq -j '.[] | select(.name=="ziti-gw01") | .id'`
-        else
-          echo " could not find gateway with name ziti-gw01"
-          exit 1
-        fi
-        verified=`curl "https://$cip:1280/gateways/$guuid" -sSX GET "${curlArgs[@]}"  --insecure  | jq -j ".data.isVerified"`
-        online=`curl "https://$cip:1280/gateways/$guuid" -sSX GET "${curlArgs[@]}"  --insecure  | jq -j ".data.isOnline"`
-        echo "Ziti Edge GW is verified - $verified"
-        echo "Ziti Edge GW is online - $online"
-        # Create Ziti Service named iperf3
-        declare -a data="{\"name\": \"iperf3\",\"protocols\": [\"tls\"],\"dns\":{\"hostname\":\"$serverIp\",\"port\": 5201},\"egressRouter\":\"$guuid\",\"endpointAddress\":\"tcp://$serverIp:5201\",\"clusters\": [\"$cuuid\"]}"
-        serviceId=`curl -sSX POST "${curlArgs[@]}" -d "${data}" "https://$cip:1280/services" --insecure | jq -j ".data.id"`
-        # Find ziti-tunnel Id for the Ziti Client
-        identities=`curl -sSX GET "${curlArgs[@]}" "https://$cip:1280/identities" --insecure  | jq -j ".data"`
-        if [[ $identities ]]; then
-          # find the identity uuid
-          tunnelId=`echo $identities | jq -j '.[] | select(.name=="ziti-tunnel") | .id'`
-        else
-          echo " could not find identity with name ziti-tunnel"
-          exit 1
-        fi
-        # Create AppWan named appwan01
-        declare -a data="{\"name\":\"appwan01\",\"identities\":[\"$tunnelId\"],\"services\":[\"$serviceId\"]}"
-        appwanId=`curl -sSX POST "${curlArgs[@]}" -d "${data}" "https://$cip:1280/app-wans" --insecure | jq -j ".data.id"`
-        echo "Appwan with ID $appwanId has been created"
-        '''
+          if [[ $gateways ]]; then
+            # find the gateway uuid
+            guuid=`echo $gateways | jq -j '.[] | select(.name=="ziti-gw01") | .id'`
+          else
+            echo " could not find gateway with name ziti-gw01"
+            exit 1
+          fi
+          verified=`curl "https://$cip:1280/gateways/$guuid" -sSX GET "${curlArgs[@]}"  --insecure  | jq -j ".data.isVerified"`
+          online=`curl "https://$cip:1280/gateways/$guuid" -sSX GET "${curlArgs[@]}"  --insecure  | jq -j ".data.isOnline"`
+          echo "Ziti Edge GW is verified - $verified"
+          echo "Ziti Edge GW is online - $online"
+          # Create Ziti Service named iperf3
+          declare -a data="{\"name\": \"iperf3\",\"protocols\": [\"tls\"],\"dns\":{\"hostname\":\"$serverIp\",\"port\": 5201},\"egressRouter\":\"$guuid\",\"endpointAddress\":\"tcp://$serverIp:5201\",\"clusters\": [\"$cuuid\"]}"
+          serviceId=`curl -sSX POST "${curlArgs[@]}" -d "${data}" "https://$cip:1280/services" --insecure | jq -j ".data.id"`
+          # Find ziti-tunnel Id for the Ziti Client
+          identities=`curl -sSX GET "${curlArgs[@]}" "https://$cip:1280/identities" --insecure  | jq -j ".data"`
+          if [[ $identities ]]; then
+            # find the identity uuid
+            tunnelId=`echo $identities | jq -j '.[] | select(.name=="ziti-tunnel") | .id'`
+          else
+            echo " could not find identity with name ziti-tunnel"
+            exit 1
+          fi
+          # Create AppWan named appwan01
+          declare -a data="{\"name\":\"appwan01\",\"identities\":[\"$tunnelId\"],\"services\":[\"$serviceId\"]}"
+          appwanId=`curl -sSX POST "${curlArgs[@]}" -d "${data}" "https://$cip:1280/app-wans" --insecure | jq -j ".data.id"`
+          echo "Appwan with ID $appwanId has been created"
+          '''
+        }
       }
     }
     stage('Test Case 01') {
